name: NodeJS with Webpack

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Running installing dependencies..."
          npm install
      - name: Run linting
        run: |
          echo "Runnung liniting tests..."
          npm run lint
        env:
          CI: true

  packages:
    name: Install Packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Running installing dependencies..."
          npm install

      - name: build run
        run: |
          echo "Running build..."
          npm run build
        env:
          CI: true

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lint, packages, build]
    steps:
      - name: Install dependencies
        run: |
          echo "Deployment in progress..."
